// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plannerv1} from '../models';

export function CreateArea(arg1:string,arg2:string):Promise<plannerv1.Area>;

export function DeleteArea(arg1:string):Promise<void>;

export function GetArea(arg1:string):Promise<plannerv1.Area>;

export function Greet(arg1:string):Promise<string>;

export function ListAreas():Promise<Array<plannerv1.Area>>;

export function UpdateArea(arg1:string,arg2:any,arg3:any):Promise<plannerv1.Area>;
